resturant-manager-master/resturant-manager-master/administration/urls.py
from administration.views import admin_change_order_status, admin_create_menu, admin_create_table, admin_create_todays_special, admin_create_user, admin_delete_contact_us, admin_delete_menu, admin_delete_order, admin_delete_reservation, admin_delete_table, admin_delete_todays_special, admin_delete_user, admin_detail_order, admin_detail_reservation, admin_edit_menu, admin_edit_order, admin_edit_reservation, admin_edit_table, admin_edit_todays_special, admin_edit_user, admin_home, admin_list_contact_us, admin_list_menu, admin_list_order, admin_list_reservation, admin_list_table, admin_list_todays_special, admin_list_user, admin_toggle_todays_special
from django.urls import path

urlpatterns = [
    path('', admin_home, name="admin_home"),
    path('all-users/', admin_list_user , name="admin_list_user" ),
    path('create-user/', admin_create_user, name="admin_create_user"),
    path('edit-user/<int:pk>/', admin_edit_user, name="admin_edit_user"),
    path('delete-user/<int:pk>/', admin_delete_user, name="admin_delete_user"),

    #Menu
    path('menu/', admin_list_menu, name="admin_list_menu"),
    path('create-menu-item/', admin_create_menu, name="admin_create_menu"),
    path('edit-menu-item/<int:pk>', admin_edit_menu, name="admin_edit_menu"),
    path('delete-menu-item/<int:pk>', admin_delete_menu, name="admin_delete_menu"),

    #Todays Special
    path('todays-special/', admin_list_todays_special, name="admin_list_todays_special"),
    path('create-todays-special/', admin_create_todays_special, name="admin_create_todays_special"),
    path('edit-todays-special/<int:pk>/', admin_edit_todays_special, name="admin_edit_todays_special"),
    path('delete-todays-special/<int:pk>/', admin_delete_todays_special, name="admin_delete_todays_special"),
    path('toggle-todays-special/<int:pk>/', admin_toggle_todays_special, name="admin_toggle_todays_special"),

    #Tables
    path('tables/', admin_list_table, name="admin_list_table"),
    path('create-table/', admin_create_table, name="admin_create_table"),
    path('edit-table/<int:pk>', admin_edit_table, name="admin_edit_table"),
    path('delete-table/<int:pk>', admin_delete_table, name="admin_delete_table"),

    #reservation
    path('reservations/',admin_list_reservation,name="admin_list_reservation"),
    path('edit-reservation/<int:pk>',admin_edit_reservation,name="admin_edit_reservation"),
    path('delete-reservation/<int:pk>',admin_delete_reservation,name="admin_delete_reservation"),
    path('detail-reservation/<int:pk>',admin_detail_reservation,name="admin_detail_reservation"),
    

    #order
    path('orders/', admin_list_order, name="admin_list_order"),
    path('edit-order/<int:pk>', admin_edit_order, name="admin_edit_order"),
    path('delete-order/<int:pk>', admin_delete_order, name="admin_delete_order"),
    path('detail-order/<int:pk>', admin_detail_order, name="admin_detail_order"),
    path('change-order-status/<int:pk>', admin_change_order_status, name="admin_change_order_status"),


    path('contact-us/', admin_list_contact_us,name="admin_list_contact_us"),
    path('delete-contact-us/<int:pk>', admin_delete_contact_us,name="admin_delete_contact_us")






]

resturant-manager-master/resturant-manager-master/base/urls.py
from accounts.views import logout
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('user.urls')),
    path('logout/', logout, name="logout"),
    path('root/', admin.site.urls),
    path('admin/', include('administration.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resturant-manager-master/resturant-manager-master/user/models.py
from resturant.models import Reservation,Table
from django.db import models
from accounts.models import User
# Create your models here.

class Food(models.Model):
    category = (
        ('1', 'Starters'),
        ('2', 'Main Course'),
        ('3', 'Desserts'),
        ('4', 'Drinks'),
        ('5', 'Other')
    )
    name = models.CharField(max_length=100,blank=False)
    category = models.CharField(max_length=15,choices=category,blank=False,default='5')
    description = models.CharField(max_length=100,blank=False)
    price = models.DecimalField(max_digits=10,blank=False,decimal_places=0)
    image = models.ImageField(upload_to='food_images/',blank=True)
    order_count = models.IntegerField(blank=False, default=0)
    is_active = models.BooleanField(default=True,blank=False)
    changed_on = models.DateTimeField(blank=False,auto_now=True)
    created_on = models.DateTimeField(blank=False,auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    
    def __str__(self):
        return self.name

class Order(models.Model):
    user = models.ForeignKey(User, blank=False, on_delete=models.CASCADE)
    reservation = models.OneToOneField(Reservation, blank=True,on_delete=models.SET_NULL,null=True)
    placed_on = models.DateTimeField(blank=False,auto_now_add=True)
    accept_status = models.BooleanField(blank=True,default=True)
    status = (
        ('1', 'Placed'),
        ('2', 'Completed')
    )
    table = models.ForeignKey(Table,on_delete=models.DO_NOTHING,blank=True,null=True)
    status = models.CharField(blank=False,choices=status,max_length=10,default='1')
    payment_type = (
        ('0','Undefined'),
        ('1','Counter'),
        ('2','Online')
        )
    payment_type = models.CharField(blank=False,choices=payment_type,max_length=10,default='0')
    receipt_id = models.CharField(max_length=100,blank=True,null=True)
    order_id = models.CharField(max_length=100,blank=True,null=True)
    payment_id = models.CharField(max_length=100,blank=True,null=True)
    signature =models.CharField(max_length=100,blank=True,null=True)
    order_response = models.JSONField(blank=True,null=True)
    payment_response = models.JSONField(blank=True,null=True)
    payment_is_complete = models.BooleanField(blank=False,default=False)
    completed_on = models.DateTimeField(blank=True,null=True)
    food = models.ManyToManyField(Food,through='FoodOrder')
    amount = models.DecimalField(max_digits=10,decimal_places=0,blank=True,null=True)
    created_on = models.DateTimeField(auto_now_add=True,blank=False)

    def __str__(self):
        return str(self.id) # TODO

class FoodOrder(models.Model):
    food = models.ForeignKey(Food,on_delete=models.CASCADE,blank=False)
    order = models.ForeignKey(Order,on_delete=models.CASCADE,blank=False)
    quantity = models.IntegerField(blank=False,default=1)
    total = models.IntegerField(blank=False,null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    changed_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.food.name) + " " + str(self.order.id)


class ContactUs(models.Model):
    email = models.EmailField(blank=False,max_length=255)
    message = models.CharField(max_length=1000,blank=False)
    created_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email + " - " + str(self.created_on)  # TODO

resturant-manager-master/resturant-manager-master/administration/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from accounts.models import User
from accounts.decorators import allowed_users
from django.contrib.auth.decorators import login_required
from accounts.forms import CreateUserForm, EditOrderForm, EditReservationForm, TableForm, TodaysSpecialForm, UserForm, FoodForm
from user.models import ContactUs, Food, FoodOrder, Order
from resturant.models import Reservation, Table, TodaysSpecial
from datetime import date,timedelta
# Create your views here.

def payment_stats():
    counter = Order.objects.filter(payment_type='1').count()
    online = Order.objects.filter(payment_type='2').count()
    if counter != 0 and online != 0:
        total = counter + online
        online_percentage = online/total*100
        counter_percentage = 100 - online_percentage
    else:
        if counter == 0:
            counter_percentage = 0
            online_percentage = 100
        elif online == 0:
            counter_percentage = 100
            online_percentage =0
    piechartdata = {
        'online':round(online_percentage),
        'counter':round(counter_percentage)
    }
    return piechartdata
def make_order_reservation_stats():
    today = date.today()
    yesterday = today - timedelta(1)
    two_days_ago = today - timedelta(2)
    three_days_ago = today - timedelta(3)
    four_days_ago = today - timedelta(4)
    five_days_ago = today - timedelta(5)
    six_days_ago = today - timedelta(6)

    order_today = Order.objects.filter(created_on=today).count()
    order_yesterday = Order.objects.filter(created_on=yesterday).count()
    order_two_days_ago= Order.objects.filter(created_on=two_days_ago).count()
    order_three_days_ago= Order.objects.filter(created_on=three_days_ago).count()
    order_four_days_ago= Order.objects.filter(created_on=four_days_ago).count()
    order_five_days_ago= Order.objects.filter(created_on=five_days_ago).count()
    order_six_days_ago= Order.objects.filter(created_on=six_days_ago).count()
    order_list = [order_six_days_ago,order_five_days_ago,order_four_days_ago,order_three_days_ago,order_two_days_ago,order_yesterday,order_today,0]

    reservation_today = Reservation.objects.filter(created_on=today).count()
    reservation_yesterday = Reservation.objects.filter(created_on=yesterday).count()
    reservation_two_days_ago= Reservation.objects.filter(created_on=two_days_ago).count()
    reservation_three_days_ago= Reservation.objects.filter(created_on=three_days_ago).count()
    reservation_four_days_ago= Reservation.objects.filter(created_on=four_days_ago).count()
    reservation_five_days_ago= Reservation.objects.filter(created_on=five_days_ago).count()
    reservation_six_days_ago= Reservation.objects.filter(created_on=six_days_ago).count()

    reservation_list = [reservation_six_days_ago,reservation_five_days_ago,reservation_four_days_ago,reservation_three_days_ago,reservation_two_days_ago,reservation_yesterday,reservation_today,0]
    output = {
        'order':order_list,
        'reservation':reservation_list
    }
    return output
    
@login_required
@allowed_users(allowed_roles=['admin'])
def admin_home(request):
    pie = payment_stats()
    order_reservation = make_order_reservation_stats()
    orders = Order.objects.filter(status='1')
    context = {
        'pie':pie,
        'orders':orders,
        'order_reservation':order_reservation
    }

    return render(request, 'administration/home.html',context)

"""
User Management Start
"""
@login_required
@allowed_users(allowed_roles=['admin'])
def admin_create_user(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST,request.FILES)
        if form.is_valid():
            user = form.save()
            messages.success(request, f'User {user.email} Created Successfully !', extra_tags="success")
            return redirect('admin_list_user')
        else:
            messages.error(request, 'Form Is Invalid Please Try Again !', extra_tags="error")    
    context = {'form':form}
    return render(request, 'administration/user/user_create.html', context)

@login_required
@allowed_users(allowed_roles=['admin'])
def admin_list_user(request):    
    user = User.objects.filter(is_admin=False)
    context = {'user':user}
    return render(request, 'administration/user/user_list.html' , context)

@login_required
@allowed_users(allowed_roles=['admin'])
def admin_edit_user(request,pk):
    try:
        user = User.objects.get(id=pk)
    except:
        messages.error(request, 'Unable TO Fetch User', extra_tags="error")    
        return redirect('admin_list_user')
    form = UserForm(instance=user)
    if request.method == "POST":
        form = UserForm(request.POST,request.FILES,instance=user)
        if form.is_valid():
            user = form.save()
            messages.success(request, f'User {user.email} saved successfully !', extra_tags="success")
            return redirect('admin_list_user')
        else:
            messages.error(request, 'Form Is Invalid Please Try Again', extra_tags="error")    
    context = {
        'user':user,
        'form':form
    }
    return render(request, 'administration/user/user_edit.html', context)

@login_required
@allowed_users(allowed_roles=['admin'])
def admin_delete_user(request,pk):
    try:
        user = User.objects.get(id=pk)
    except:
        messages.error(request, 'Unable TO Fetch User', extra_tags="error")    
        return redirect('admin_list_user')
    if user:
        user.delete()
        messages.success(request, 'User Deleted Successfully !', extra_tags="success")   
    return redirect('admin_list_user')     

"""
User Management End
"""    

"""
Menu Management Start
"""
@login_required
@allowed_users(allowed_roles=['admin'])
def admin_list_menu(request):
    menu_starters = Food.objects.filter(category='1') 
    menu_main_dishes = Food.objects.filter(category='2') 
    menu_desserts = Food.objects.filter(category='3') 
    menu_drinks = Food.objects.filter(category='4') 
    menu_other = Food.objects.filter(category='5') 

    context = {
        'menu_starters':menu_starters,
        'menu_main_dishes':menu_main_dishes,
        'menu_desserts':menu_desserts,
        'menu_drinks':menu_drinks,
        'menu_other':menu_other
    }
    return render(request, 'administration/menu/menu_list.html', context)

@login_required
@allowed_users(allowed_roles=['admin'])
def admin_create_menu(request):
    form = FoodForm()
    if request.method == "POST":
        form = FoodForm(request.POST,request.FILES)
        if form.is_valid():
            food = form.save(commit=False)
            food.created_by = request.user
            food.save()
            messages.success(request, f'Food Item {food.name} Saved Successfully !', extra_tags="success")
            return redirect('admin_list_menu')
        else:
            messages.error(request, 'Form Is Invalid Please Check The Form !', extra_tags="error")   
    context = {
        'form':form
    }
    return render(request, 'administration/menu/menu_create.html', context)

@login_required
@allowed_users(allowed_roles=['admin'])
def admin_edit_menu(request,pk):
    try:
        food = Food.objects.get(id=pk)
    except:
        messages.error(request, 'Unable To Fetch Food Item !', extra_tags="error")    
        return redirect('admin_list_menu')
    form = FoodForm(instance=food)
    if request.method == "POST":
        form = FoodForm(request.POST,request.FILES,instance=food)
        if form.is_valid():
            form.save()
            messages.success(request, f'Food Item - {food.name} saved successfully !',extra_tags="success")
            return redirect('admin_list_menu')
        else:
            messages.error(request, 'Form Invalid Please Check The Form !', )    
    context = {
        "food":food,
        "form":form
    }        
    return render(request, 'administration/menu/menu_edit.html', context)

@login_required
@allowed_users(allowed_roles=['admin'])
def admin_delete_menu(request,pk):
    try:
        food = Food.objects.get(id=pk)
    except:
        messages.error(request, 'Unable TO Fetch Food Item', extra_tags="error")    
        return redirect('admin_list_menu')
    if food:
        food.delete()
        messages.success(request, 'Food Item Deleted Successfully !', extra_tags="success")   
    return redirect('admin_list_menu')     
"""
Menu Management End
"""

"""
Todays Special Management Start
"""

@login_required
@allowed_users(allowed_roles=['admin'])
def admin_list_todays_special(request):
    todays_special = TodaysSpecial.objects.all()
    context = {
        'todays_special':todays_special
    }
    return render(request, 'administration/todays_special/todays_special_list.html', context)

@login_required
@allowed_users(allowed_roles=['admin'])
def admin_create_todays_special(request):
    form = TodaysSpecialForm()
    if request.method == "POST":
        form = TodaysSpecialForm(request.POST, request.FILES)
        if form.is_valid():
            todays_special = form.save(commit=False)
            todays_special.created_by = request.user
            todays_special.save()
            messages.success(request, f"Today's Special {todays_special.name} added successfully !", extra_tags="success")
            return redirect('admin_list_todays_special')
        else:
            messages.error(request, 'Form Invalid Please Check The Form !', extra_tags="error")
    context = {"form":form}        
    return render(request, 'administration/todays_special/todays_special_create.html', context)            

@login_required
@allowed_users(allowed_roles=['admin'])
def admin_edit_todays_special(request, pk):
    try:
        todays_special = TodaysSpecial.objects.get(id=pk)
    except:
        messages.error(request, "Unable To Fetch Today's Special Item !",extra_tags="error")    
        return redirect('admin_list_todays_special')

resturant-manager-master/resturant-manager-master/templates/administration/order/order_detail.html
{% extends 'administration/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Detail Order - #{{order.id}}
{% endblock title %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Order Details&nbsp;&nbsp;&nbsp;<small><a href="{% url 'admin_edit_order' order.id %}">Edit This Order</a></small></h4>
                        <p class="category">Details Of Order #{{order.id}}</p>

                    </div>
                    <br>
                    <div class="row " style="padding:10px;">
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">User</div>
                                <div class="panel-body">
                                    <a href="{% url 'admin_edit_user' order.user.id %}">
                                        {{order.user}}
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Reservation</div>
                                <div class="panel-body">
                                    {% if order.reservation %}
                                    <a href="{% url 'admin_edit_reservation' order.reservation.id %}">
                                        #{{order.reservation.id}} - {{order.reservation.number_of_persons}}
                                    </a>
                                    {% else %}
                                    Unreserved
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Placed On</div>
                                <div class="panel-body">
                                    {{order.placed_on}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Accept Status</div>
                                <div class="panel-body">
                                    {{order.accept_status}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Table</div>
                                <div class="panel-body">
                                    {% if order.table %}
                                    <a href="{% url 'admin_edit_table' order.table.id %}">
                                        {{order.table}}
                                    </a>
                                    {% else %}
                                    No Table Assigned
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Status</div>
                                <div class="panel-body">
                                    {{order.get_status_display}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Payment Type</div>
                                <div class="panel-body">
                                    {{order.get_payment_type_display}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Payment Status</div>
                                <div class="panel-body">
                                    {% if order.payment_is_complete %}
                                    Complete
                                    {% else %}
                                    Pending
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Total Amount</div>
                                <div class="panel-body">
                                    &#8377; {{order.amount}}
                                </div>
                            </div>
                        </div>
                        {% if order.receipt_id %}
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Receipt Id</div>
                                <div class="panel-body">
                                    {{order.receipt_id}}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if order.order_id %}
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Razorpay Order Id</div>
                                <div class="panel-body">
                                    {{order.order_id}}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if order.payment_id %}
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Razorpay Payment Id</div>
                                <div class="panel-body">
                                    {{order.payment_id}}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">Food Items:</div>
                                <div class="panel-body" style="text-overflow: ellipsis;">
                                    {% if food %}
                                    {% for i in food %}
                                    <a href="{% url 'admin_edit_menu' i.food.id %}">{{i.food.name}}</a> <b>x{{i.quantity}}</b> | 
                                    {% endfor %}
                                    {% else %}
                                    No Food Items Found For This Order
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        
                        {% if order.order_response %}
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">Razorpay Order Response</div>
                                <div class="panel-body" style="text-overflow: ellipsis;">
                                    {{order.order_response}}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if order.payment_response %}
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">Razorpay Payment Response</div>
                                <div class="panel-body" style="text-overflow: ellipsis;">
                                    {{order.payment_response}}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% if order.signature %}
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">Razorpay Signature</div>
                                <div class="panel-body" style="text-overflow: ellipsis;">
                                    {{order.signature}}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                            
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
<script>
    $('input[name=completed_on]').attr('type', 'date');
    $('input[name=time]').attr('type', 'time');
</script>

{% endblock extrajs %}

resturant-manager-master/resturant-manager-master/templates/administration/order/order_list.html
{% extends 'administration/base.html' %}
{% block title %}
All Orders
{% endblock title %}

{% block extracss %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
{% endblock extracss %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <div style="display: flex;">
                            <h4 class="title">All Orders</h4>
                            <!--
                            <a href="{% url 'admin_create_table' %}" style="margin-left: 10px;"
                                class="btn btn-success">
                                <i class="fa fa-plus"></i>
                            </a>
                            -->
                        </div>

                        <p class="category">Manage Orders</p>
                    </div>
                    <div class="content table-responsive table-full-width" style="margin:10px;">
                        <table class="table table-hover table-striped datatable">
                            <thead>
                                <th>Number</th>
                                <th>Table</th>
                                <th>Payment Type</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </thead>
                            <tbody>
                                {% for i in order %}
                                <tr>
                                    <td>#{{i.id}}</td>
                                    <td>
                                            {{i.table}}
                                        
                                    </td>
                                    <td>
                                        {{i.get_payment_type_display}}
                                    </td>
                                    <td>
                                        {{i.get_status_display}}
                                    </td>
                                    <td>
                                        <a href="{% url 'admin_edit_order' i.id %}"
                                            class="btn btn-warning btn-sm">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a href="{% url 'admin_delete_order' i.id %}"
                                            class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                        <a href="{% url 'admin_detail_order' i.id %}"
                                            class="btn btn-primary btn-sm">
                                            <i class="fa fa-arrow-right"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function () {
        $('.datatable').DataTable();
        $('.sidebar-wrapper .nav li').removeClass('active');
        $('#nav-order').addClass('active');
    });
</script>
{% endblock extrajs %}