resturant-manager-master/resturant-manager-master/administration/urls.py
from administration.views import admin_change_order_status, admin_create_menu, admin_create_table, admin_create_todays_special, admin_create_user, admin_delete_contact_us, admin_delete_menu, admin_delete_order, admin_delete_reservation, admin_delete_table, admin_delete_todays_special, admin_delete_user, admin_detail_order, admin_detail_reservation, admin_edit_menu, admin_edit_order, admin_edit_reservation, admin_edit_table, admin_edit_todays_special, admin_edit_user, admin_home, admin_list_contact_us, admin_list_menu, admin_list_order, admin_list_reservation, admin_list_table, admin_list_todays_special, admin_list_user, admin_toggle_todays_special
from django.urls import path

urlpatterns = [
    path('', admin_home, name="admin_home"),
    path('all-users/', admin_list_user , name="admin_list_user" ),
    path('create-user/', admin_create_user, name="admin_create_user"),
    path('edit-user/<int:pk>/', admin_edit_user, name="admin_edit_user"),
    path('delete-user/<int:pk>/', admin_delete_user, name="admin_delete_user"),

    #Menu
    path('menu/', admin_list_menu, name="admin_list_menu"),
    path('create-menu-item/', admin_create_menu, name="admin_create_menu"),
    path('edit-menu-item/<int:pk>', admin_edit_menu, name="admin_edit_menu"),
    path('delete-menu-item/<int:pk>', admin_delete_menu, name="admin_delete_menu"),

    #Todays Special
    path('todays-special/', admin_list_todays_special, name="admin_list_todays_special"),
    path('create-todays-special/', admin_create_todays_special, name="admin_create_todays_special"),
    path('edit-todays-special/<int:pk>/', admin_edit_todays_special, name="admin_edit_todays_special"),
    path('delete-todays-special/<int:pk>/', admin_delete_todays_special, name="admin_delete_todays_special"),
    path('toggle-todays-special/<int:pk>/', admin_toggle_todays_special, name="admin_toggle_todays_special"),

    #Tables
    path('tables/', admin_list_table, name="admin_list_table"),
    path('create-table/', admin_create_table, name="admin_create_table"),
    path('edit-table/<int:pk>', admin_edit_table, name="admin_edit_table"),
    path('delete-table/<int:pk>', admin_delete_table, name="admin_delete_table"),

    #reservation
    path('reservations/',admin_list_reservation,name="admin_list_reservation"),
    path('edit-reservation/<int:pk>',admin_edit_reservation,name="admin_edit_reservation"),
    path('delete-reservation/<int:pk>',admin_delete_reservation,name="admin_delete_reservation"),
    path('detail-reservation/<int:pk>',admin_detail_reservation,name="admin_detail_reservation"),
    

    #order
    path('orders/', admin_list_order, name="admin_list_order"),
    path('edit-order/<int:pk>', admin_edit_order, name="admin_edit_order"),
    path('delete-order/<int:pk>', admin_delete_order, name="admin_delete_order"),
    path('detail-order/<int:pk>', admin_detail_order, name="admin_detail_order"),
    path('change-order-status/<int:pk>', admin_change_order_status, name="admin_change_order_status"),


    path('contact-us/', admin_list_contact_us,name="admin_list_contact_us"),
    path('delete-contact-us/<int:pk>', admin_delete_contact_us,name="admin_delete_contact_us")






]

resturant-manager-master/resturant-manager-master/base/urls.py
from accounts.views import logout
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('user.urls')),
    path('logout/', logout, name="logout"),
    path('root/', admin.site.urls),
    path('admin/', include('administration.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resturant-manager-master/resturant-manager-master/resturant/models.py
from django.db import models
from accounts.models import User
# Create your models here.

class Table(models.Model):
    number = models.IntegerField(blank=False)
    capacity = models.IntegerField(blank=False)
    status = models.BooleanField(blank=False, default=False)
    is_occupied = models.BooleanField(default=False,blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"#{self.number} ({self.capacity} Persons)"  # TODO

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True,null=True)
    name = models.CharField(max_length=255,blank=False,null=False)
    email = models.EmailField(blank=False,null=False)
    phone = models.DecimalField(max_digits=10,decimal_places=0,blank=False)
    n = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5),
        (6,6),
        (7,7),
        (8,8),
        (9,9),
        (10,10),
    )
    number_of_persons = models.IntegerField(choices=n,blank=False)
    date = models.CharField(max_length=100,blank=False,null=False,default="May 5")
    time = models.CharField(blank=False,max_length=100)
    food = (
        ('indian', 'INDIAN'),
        ('chinese', 'CHINESE'),     
        ('italian', 'ITALIAN'),
        ('thai', 'THAI'),           
        ('no_pref', 'NO PREFERENCE')
    )
    preferred_food = models.CharField(choices=food, max_length=100,blank=True)
    occation = (
        ('birthday', 'Birthday'),
        ('wedding', 'Wedding'),
        ('anniversary', 'Anniversary'),
        ('casual', 'Casual')
    )
    occation = models.CharField(choices=occation,blank=True,max_length=100)
    table = models.ForeignKey(Table, on_delete=models.DO_NOTHING,blank=True,null=True)
    status = (
        ('reserved','Reserved'),
        ('unreserved','Unreserved'),
        ('undefined','Undefined')
    )
    is_expired = models.BooleanField(blank=False,default=False)
    status = models.CharField(choices=status,blank=True,max_length=10,default='undefined') 
    created_on = models.DateTimeField(auto_now_add=True,blank=False)
    changed_on = models.DateTimeField(auto_now=True,blank=False)

    def __str__(self):
        return str(self.email) + "-" + str(self.created_on) # TODO

class TodaysSpecial(models.Model):
    name = models.CharField(max_length=20,blank=False)
    description = models.CharField(max_length=100,blank=False) 
    image = models.ImageField(upload_to='todays_special/',blank=False)
    is_active = models.BooleanField(default=True, blank=False)
    created_on = models.DateField(auto_now_add=True,blank=False)
    changed_on = models.DateField(auto_now=True,blank=False)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.name # TODO      

resturant-manager-master/resturant-manager-master/user/models.py
from resturant.models import Reservation,Table
from django.db import models
from accounts.models import User
# Create your models here.

class Food(models.Model):
    category = (
        ('1', 'Starters'),
        ('2', 'Main Course'),
        ('3', 'Desserts'),
        ('4', 'Drinks'),
        ('5', 'Other')
    )
    name = models.CharField(max_length=100,blank=False)
    category = models.CharField(max_length=15,choices=category,blank=False,default='5')
    description = models.CharField(max_length=100,blank=False)
    price = models.DecimalField(max_digits=10,blank=False,decimal_places=0)
    image = models.ImageField(upload_to='food_images/',blank=True)
    order_count = models.IntegerField(blank=False, default=0)
    is_active = models.BooleanField(default=True,blank=False)
    changed_on = models.DateTimeField(blank=False,auto_now=True)
    created_on = models.DateTimeField(blank=False,auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    
    def __str__(self):
        return self.name

class Order(models.Model):
    user = models.ForeignKey(User, blank=False, on_delete=models.CASCADE)
    reservation = models.OneToOneField(Reservation, blank=True,on_delete=models.SET_NULL,null=True)
    placed_on = models.DateTimeField(blank=False,auto_now_add=True)
    accept_status = models.BooleanField(blank=True,default=True)
    status = (
        ('1', 'Placed'),
        ('2', 'Completed')
    )
    table = models.ForeignKey(Table,on_delete=models.DO_NOTHING,blank=True,null=True)
    status = models.CharField(blank=False,choices=status,max_length=10,default='1')
    payment_type = (
        ('0','Undefined'),
        ('1','Counter'),
        ('2','Online')
        )
    payment_type = models.CharField(blank=False,choices=payment_type,max_length=10,default='0')
    receipt_id = models.CharField(max_length=100,blank=True,null=True)
    order_id = models.CharField(max_length=100,blank=True,null=True)
    payment_id = models.CharField(max_length=100,blank=True,null=True)
    signature =models.CharField(max_length=100,blank=True,null=True)
    order_response = models.JSONField(blank=True,null=True)
    payment_response = models.JSONField(blank=True,null=True)
    payment_is_complete = models.BooleanField(blank=False,default=False)
    completed_on = models.DateTimeField(blank=True,null=True)
    food = models.ManyToManyField(Food,through='FoodOrder')
    amount = models.DecimalField(max_digits=10,decimal_places=0,blank=True,null=True)
    created_on = models.DateTimeField(auto_now_add=True,blank=False)

    def __str__(self):
        return str(self.id) # TODO

class FoodOrder(models.Model):
    food = models.ForeignKey(Food,on_delete=models.CASCADE,blank=False)
    order = models.ForeignKey(Order,on_delete=models.CASCADE,blank=False)
    quantity = models.IntegerField(blank=False,default=1)
    total = models.IntegerField(blank=False,null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    changed_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.food.name) + " " + str(self.order.id)


class ContactUs(models.Model):
    email = models.EmailField(blank=False,max_length=255)
    message = models.CharField(max_length=1000,blank=False)
    created_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email + " - " + str(self.created_on)  # TODO

resturant-manager-master/resturant-manager-master/templates/administration/reservation/reservation_detail.html
{% extends 'administration/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Detail Reservation - #{{reservation.id}}
{% endblock title %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Reservation Details&nbsp;&nbsp;&nbsp;<small><a
                                    href="{% url 'admin_edit_reservation' reservation.id %}">Edit This
                                    Reservation</a></small></h4>
                        <p class="category">Details Of Reservation #{{reservation.id}}</p>

                    </div>
                    <br>
                    <div class="row " style="padding:10px;">
                        {% if reservation.user %}
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">User</div>
                                <div class="panel-body">
                                    <a href="{% url 'admin_edit_user' reservation.user.id %}">
                                        {{reservation.user}}
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Name</div>
                                <div class="panel-body">
                                    {{reservation.name}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Email</div>
                                <div class="panel-body">
                                    {{reservation.email}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Phone</div>
                                <div class="panel-body">
                                    {{reservation.phone}}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Number Of Persons</div>
                                <div class="panel-body">
                                    {{reservation.number_of_persons}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Date</div>
                                <div class="panel-body">
                                    {{reservation.date}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Time</div>
                                <div class="panel-body">
                                    {{reservation.time}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Preferred Food</div>
                                <div class="panel-body">
                                    {{reservation.get_preferred_food_display}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Occation</div>
                                <div class="panel-body">
                                    {{reservation.get_occation_display}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Table</div>
                                <div class="panel-body">
                                    {% if reservation.table %}
                                    <a href="{% url 'admin_edit_table' reservation.table.id %}">{{reservation.table}}</a>
                                    {% else %}
                                    No Table Assigned
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Expired</div>
                                <div class="panel-body">
                                    {% if reservation.is_expired %}
                                    Yes
                                    {% else %}
                                    No
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Status</div>
                                <div class="panel-body">
                                    {{reservation.get_status_display}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Created On</div>
                                <div class="panel-body">
                                    {{reservation.created_on}}
                                </div>
                            </div>
                        </div><div class="col-sm-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">Changed On</div>
                                <div class="panel-body">
                                    {{reservation.changed_on}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
<script>
    $('input[name=completed_on]').attr('type', 'date');
    $('input[name=time]').attr('type', 'time');
</script>

{% endblock extrajs %}

resturant-manager-master/resturant-manager-master/templates/administration/reservation/reservation_edit.html
{% extends 'administration/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Edit Reservation
{% endblock title %}
    
{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Edit Reservation</h4>
                        <p class="category">Editing Reservation #{{reservation.id}}</p>
                    </div>
                    <div class="content table-responsive table-full-width" style="margin:10px;">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form|crispy}}
                            <button class="btn btn-success" type="submit">Submit</button>
                        </form>
                       <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
<script>
$('input[name=date]').attr('type', 'date');
$('input[name=time]').attr('type', 'time');

</script>
    
{% endblock extrajs %}
    

resturant-manager-master/resturant-manager-master/templates/administration/reservation/reservation_list.html
{% extends 'administration/base.html' %}
{% block title %}
All Reservations
{% endblock title %}

{% block extracss %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
{% endblock extracss %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <div style="display: flex;">
                            <h4 class="title">All Reservations</h4>
                            <!--
                            <a href="{% url 'admin_create_table' %}" style="margin-left: 10px;"
                                class="btn btn-success">
                                <i class="fa fa-plus"></i>
                            </a>-->
                        </div>

                        <p class="category">Manage Reservations</p>
                    </div>
                    <div class="content table-responsive table-full-width" style="margin:10px;">
                        <table class="table table-hover table-striped datatable">
                            <thead>
                                <th>Number</th>
                                <th>Email</th>
                                <th>Date</th>
                                <th>Table</th>
                                <th>Actions</th>
                            </thead>
                            <tbody>
                                {% for i in reservation %}
                                <tr>
                                    <td>#{{i.id}}</td>
                                    <td>
                                        <a href="{% url 'admin_detail_reservation' i.id %}">
                                            {{i.email}}
                                        </a>
                                    </td>
                                    <td>
                                        {{i.date}}
                                    </td>
                                    <td>
                                        Table #{{i.table.number}}
                                    </td>
                                    <td>
                                        <a href="{% url 'admin_edit_reservation' i.id %}"
                                            class="btn btn-warning btn-sm">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a href="{% url 'admin_delete_reservation' i.id %}"
                                            class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function () {
        $('.datatable').DataTable();
        $('.sidebar-wrapper .nav li').removeClass('active');
        $('#nav-reservation').addClass('active');
    });
</script>
{% endblock extrajs %}