resturant-manager-master/resturant-manager-master/base/urls.py
from accounts.views import logout
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('user.urls')),
    path('logout/', logout, name="logout"),
    path('root/', admin.site.urls),
    path('admin/', include('administration.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resturant-manager-master/resturant-manager-master/user/urls.py
from django.urls import path
from .views import authenticate, contact_us_backend, home, login, order, order_confirmation, order_payment, payment_success, register, reservation_backend, user

urlpatterns = [
    path('', home, name="home"),
    path('u/<str:pk>', user, name="user"),
    path('order/', order, name="order"),
    path('confirm-order/<int:pk>/', order_confirmation, name="order_confirmation"),
    path('payment/<int:pk>/', order_payment, name="order_payment"),
    path('payment/success/<int:pk>/', payment_success, name="payment_success"),
    path('contact-us/',contact_us_backend,name='contact_us'),

    path('authenticate/', authenticate, name="authenticate"),
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('reservation-backend/', reservation_backend, name="reservation_backend")
]

resturant-manager-master/resturant-manager-master/user/models.py
from resturant.models import Reservation,Table
from django.db import models
from accounts.models import User
# Create your models here.

class Food(models.Model):
    category = (
        ('1', 'Starters'),
        ('2', 'Main Course'),
        ('3', 'Desserts'),
        ('4', 'Drinks'),
        ('5', 'Other')
    )
    name = models.CharField(max_length=100,blank=False)
    category = models.CharField(max_length=15,choices=category,blank=False,default='5')
    description = models.CharField(max_length=100,blank=False)
    price = models.DecimalField(max_digits=10,blank=False,decimal_places=0)
    image = models.ImageField(upload_to='food_images/',blank=True)
    order_count = models.IntegerField(blank=False, default=0)
    is_active = models.BooleanField(default=True,blank=False)
    changed_on = models.DateTimeField(blank=False,auto_now=True)
    created_on = models.DateTimeField(blank=False,auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    
    def __str__(self):
        return self.name

class Order(models.Model):
    user = models.ForeignKey(User, blank=False, on_delete=models.CASCADE)
    reservation = models.OneToOneField(Reservation, blank=True,on_delete=models.SET_NULL,null=True)
    placed_on = models.DateTimeField(blank=False,auto_now_add=True)
    accept_status = models.BooleanField(blank=True,default=True)
    status = (
        ('1', 'Placed'),
        ('2', 'Completed')
    )
    table = models.ForeignKey(Table,on_delete=models.DO_NOTHING,blank=True,null=True)
    status = models.CharField(blank=False,choices=status,max_length=10,default='1')
    payment_type = (
        ('0','Undefined'),
        ('1','Counter'),
        ('2','Online')
        )
    payment_type = models.CharField(blank=False,choices=payment_type,max_length=10,default='0')
    receipt_id = models.CharField(max_length=100,blank=True,null=True)
    order_id = models.CharField(max_length=100,blank=True,null=True)
    payment_id = models.CharField(max_length=100,blank=True,null=True)
    signature =models.CharField(max_length=100,blank=True,null=True)
    order_response = models.JSONField(blank=True,null=True)
    payment_response = models.JSONField(blank=True,null=True)
    payment_is_complete = models.BooleanField(blank=False,default=False)
    completed_on = models.DateTimeField(blank=True,null=True)
    food = models.ManyToManyField(Food,through='FoodOrder')
    amount = models.DecimalField(max_digits=10,decimal_places=0,blank=True,null=True)
    created_on = models.DateTimeField(auto_now_add=True,blank=False)

    def __str__(self):
        return str(self.id) # TODO

class FoodOrder(models.Model):
    food = models.ForeignKey(Food,on_delete=models.CASCADE,blank=False)
    order = models.ForeignKey(Order,on_delete=models.CASCADE,blank=False)
    quantity = models.IntegerField(blank=False,default=1)
    total = models.IntegerField(blank=False,null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    changed_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.food.name) + " " + str(self.order.id)


class ContactUs(models.Model):
    email = models.EmailField(blank=False,max_length=255)
    message = models.CharField(max_length=1000,blank=False)
    created_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email + " - " + str(self.created_on)  # TODO

resturant-manager-master/resturant-manager-master/user/views.py
from django import contrib
from accounts.forms import ContactUsForm, ProfileEditForm, ReservationForm
import hmac
import hashlib
from resturant.models import Reservation, TodaysSpecial
from django.contrib import messages
from django.contrib.auth.models import Group
from django.views.decorators.csrf import csrf_exempt
from accounts.models import User
from .models import Food, FoodOrder, Order, Table
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from base.settings import DOMAIN, RAZORPAY_CLIENT, RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET
from django.contrib.auth.hashers import make_password
from accounts.decorators import admin_not_allowed, unauthenticated_user
# Create your views here.
@admin_not_allowed
def home(request):
    starters = Food.objects.filter(category='1', is_active=True)
    main_dishes = Food.objects.filter(category='2', is_active=True)
    desserts = Food.objects.filter(category='3', is_active=True)
    drinks = Food.objects.filter(category='4', is_active=True)
    other = Food.objects.filter(category='5', is_active=True)
    menu = {
        'starters':starters,
        'main_dishes':main_dishes,
        'desserts':desserts,
        'drinks':drinks,
        'other':other
    }
    todays_special = TodaysSpecial.objects.filter(is_active=True)
    new_reservationform = ReservationForm()
    context = {
        'domain':DOMAIN,
        'menu':menu,
        'todays_special':todays_special,
        'new_reservationform':new_reservationform
    }
    return render(request, 'user/home.html',context)

def reservation_backend(request):
    reservation = None
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        email = request.POST.get('email')
        print(form)
        if form.is_valid():
            if email:
                user = User.objects.filter(email=email)
                if user:
                    try:
                        user = User.objects.get(email=email)
                        is_user = True
                    except:
                        messages.error(request, 'Unable To Fetch User With This Email', extra_tags="error")    
                else:
                    is_user = None
                if is_user and user:
                    reservation = form.save()    
                    reservation.user = user
                    reservation.save()
                else:
                    reservation = form.save()
                    messages.success(request,'Successfully Reserved', extra_tags="success")    
                people = reservation.number_of_persons
                tables = Table.objects.filter(is_occupied=False,status=True)
                print(tables)
                if tables:
                    for table in tables:
                        print('baba')
                        if table.capacity == people:
                                selected_table = table
                                break
                        elif table.capacity > people:
                                selected_table = table
                                break
                        else:
                                selected_table = None
                    print(selected_table)
                    if selected_table:
                        reservation.table = selected_table
                        selected_table.is_occupied = True
                        reservation.save()
                        selected_table.save()
                    messages.success(request, f'Successfully Reserved Table #{selected_table.number}', extra_tags="success")
            else:
                messages.error(request, 'Email Is Required !', extra_tags="error")        
        else:
            messages.error(request,'Form Invalid Please Check The Form')
    else:
        messages.error(request, 'Only Post requests allowed at this endpoint')    
    return redirect('home')    

@admin_not_allowed
@unauthenticated_user
def authenticate(request):
    return render(request, 'user/login.html',{'domain' : DOMAIN})    

#@unauthenticated_user
def login(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = User.objects.filter(email=email)
        if not user:
            messages.error(request, 'Email Not Registered !', extra_tags="error")
            return redirect('authenticate')
        else:
            user = auth.authenticate(username=email,password=password)
            if user:
                auth.login(request, user)
                return redirect('home')
            else:
                messages.error(request, 'Invalid Credentials !', extra_tags="error")
                return redirect('authenticate')
    else:
        messages.error(request, 'Only Post Requests Are Allowed On This Endpoint', extra_tags="error")
    return redirect('authenticate')            

def register(request):
    if request.method == "POST":
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        check = User.objects.filter(email=email)
        if check:
            messages.error(request, 'Email Address Already registered!', extra_tags="error")
            return redirect('authenticate')
        phone = request.POST.get('phone')
        check = User.objects.filter(phone=phone)
        if check:
            messages.error(request, 'User with this phone number already exists!', extra_tags="error")
            return redirect('authenticate')    
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if fname and lname and email and phone and password1 and password2:
            if password1 == password2:
                user = User.objects.create(fname=fname,lname=lname,email=email,phone=phone,password=make_password(password1))    
                group = Group.objects.get_or_create(name="customer")
                user.groups.add(group[0])
                user.save()
                if user:
                    messages.success(request, 'Successfully Registered You Can Login Now !', extra_tags="success")
                else:
                    messages.error(request, 'Unable To Create User', extra_tags="error")
            else:
                messages.error(request, 'Passwords Do Not Match !', extra_tags="error")
        else:
            messages.error(request, 'Form Incomplete Please Check The Form', extra_tags="error")                
    else:
        messages.error(request, 'Only Post Requests Are Allowed On This Endpoint', extra_tags="error")
    return redirect('authenticate')            

@admin_not_allowed
@login_required
def user(request,pk):
    profile_edit_form = ProfileEditForm(instance=request.user)
    orders = Order.objects.filter(user=request.user)
    reservations = Reservation.objects.filter(user=request.user)
    food_order = None
    for order in orders:
        food = FoodOrder.objects.filter(order=order)
        if food_order:
            food_order = food_order | food
        else:
            food_order = food   
    
    if request.method == "POST":
        profile_edit_form = ProfileEditForm(request.POST,request.FILES,instance=request.user)
        if profile_edit_form.is_valid():
            profile_edit_form.save()
            messages.success(request, 'Profile Changed Successfully', extra_tags="success")
            return redirect('user',pk=request.user.email)
        else:
            messages.error(request, 'Form Invalid Please Check The Form', extra_tags="error")    
    context = {
        'domain':DOMAIN,
        'form':profile_edit_form,
        'orders':orders,
        'food_order':food_order,
        'reservations':reservations
        }
    return render(request, 'user/user.html',context)

@admin_not_allowed
def order(request):
    price = user_has_reserved = 0
    if not request.user.is_authenticated:
        messages.error(request, 'Please Login/Register To Order', extra_tags="error")
        return redirect('authenticate')
    food = Food.objects.filter(is_active=True)
    table = Table.objects.filter(is_occupied=False,status=True)
    if Reservation.objects.filter(user=request.user,is_expired=False):
        user_has_reserved = True
    if request.method == "POST":
        order = Order.objects.create(user=request.user)
        if not user_has_reserved:
            if not request.POST.get('table'):
                print(request.POST)
                messages.error(request,'Please Select Table', extra_tags="error")
                return redirect('order')
        loop_count = 0
        selected_table = request.POST.get('table')
        if user_has_reserved:    
            reservation = Reservation.objects.get_or_create(user=request.user,is_expired=False)
            if reservation:
                selected_table = reservation[0].table 
                reservation[0].order = order
                reservation[0].status = 'reserved'
                reservation[0].is_expired = True
                reservation[0].save()
        else:        
            try:
                selected_table = Table.objects.get(id=selected_table)
            except:
                messages.error(request, 'Unable to assign that table', extra_tags="error")
        if selected_table:
            order.table = selected_table
        for i in request.POST:
            if i.isnumeric():
                item_qty = int(request.POST.get(i))
                if item_qty > 0:
                    try:
                        food_item = Food.objects.get(id=i)
                    except:
                        print("error: Unable To Fetch Food Item")
                    if food_item and item_qty:   
                        item_price = food_item.price * item_qty 
                        price = price + item_price

resturant-manager-master/resturant-manager-master/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">
  <!-- Site Metas -->
  <title>Sudama Resturant | {% block title %}{% endblock title %}</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- Site Icons -->
  <link rel="shortcut icon" href="{% static 'user/images/favicon.ico' %}" type="image/x-icon" />
  <link rel="apple-touch-icon" href="{% static 'user/images/apple-touch-icon.png' %}">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'user/css/bootstrap.min.css' %}">
  <!-- Site CSS -->
  <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
  <!-- Responsive CSS -->
  <link rel="stylesheet" href="{% static 'user/css/responsive.css' %}">
  <!-- color -->
  <link id="changeable-colors" rel="stylesheet" href="{% static 'user/css/colors/orange.css' %}" />
  <!-- Modernizer -->
  <script src="{% static 'user/js/modernizer.js' %}"></script>
  {% block extracss %}{% endblock extracss %}
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
  {% include 'user/navbar.html' %}
  <!-- end site-header -->
  {% block content %}{% endblock content %}
  <!-- end reservations-main -->
  {% include 'user/footer.html' %}
  <!-- end footer-main -->
  <a href="#" class="scrollup" style="display: none;">Scroll</a>
  <!-- ALL JS FILES -->
  <script src="{% static 'user/js/all.js' %}"></script>
  <script src="{% static 'user/js/bootstrap.min.js' %}"></script>
  <!-- ALL PLUGINS -->
  <script src="{% static 'user/js/custom.js' %}"></script>
  {% block extrajs %}{% endblock extrajs %}
</body>

</html>

resturant-manager-master/resturant-manager-master/templates/user/footer.html
{% load static %}
{% for message in messages %}
{% if "success" in message.tags %}
<script>
    alert('Success!! {{message}}');
</script>
{% elif "error" in message.tags %}
<script>
    alert('Error!! {{message}}');
</script>
{% endif %}
{% endfor %}
<div id="footer" class="footer-main">
    <div class="footer-news pad-top-100 pad-bottom-70 parallax">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="wow fadeIn" data-wow-duration="1s" data-wow-delay="0.1s">
                        <h2 class="ft-title color-white text-center"> Contact Us </h2>
                        <p> For Any Queries, Suggestions, Reviews Please Feel Free To Message Us</p>
                    </div>
                    <form method="POST" action="{% url 'contact_us' %}">
                        {% csrf_token %}
                        <input type="email" name="email" id="id_email" placeholder="Enter your e-mail id" required>
                        <input name="message" id="id_message" style="margin-top: 10px;" type="text" placeholder="Your Message" required>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="reserve-book-btn text-center">
                                <button class="hvr-underline-from-center" style="color: white;" type="submit">Send </button>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end footer-news -->
    <img src="{% static 'user/images/ad_2.png' %}" alt="" style="width:100%;height:auto;">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15088.743907150827!2d73.02716386977539!3d19.011524900000005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c3da99fe4209%3A0xf423b7b290871fba!2sSUDHAMA%20VEG%20RESTAURANT!5e0!3m2!1sen!2sin!4v1620197103844!5m2!1sen!2sin" width="100%" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    <div class="footer-box pad-top-70">
        <div class="container">
            <div class="row">
                <div class="footer-in-main">
                    <div class="footer-logo">
                        <div class="text-center">
                            <img src="{% static 'user/images/logo.png' %}" alt="" />
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="footer-box-a">
                            <h3>About Us</h3>
                            <p>Sudama Resturant is one of the top fine dine places in the city.</p>
                            <ul class="socials-box footer-socials pull-left">
                                <li>
                                    <a href="#">
                                        <div class="social-circle-border"><i class="fa  fa-facebook"></i></div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="social-circle-border"><i class="fa fa-twitter"></i></div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="social-circle-border"><i class="fa fa-google-plus"></i></div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="social-circle-border"><i class="fa fa-pinterest"></i></div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="social-circle-border"><i class="fa fa-linkedin"></i></div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- end footer-box-a -->
                    </div>
                    <!-- end col -->
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="footer-box-b">
                            <h3>New Menu</h3>
                            <ul>
                                <li><a href="javasctipt:void(0);">Italian Bomba Sandwich</a></li>
                                <li><a href="javasctipt:void(0);">Double Dose of Pork Belly</a></li>
                                <li><a href="javasctipt:void(0);">Spicy Thai Noodles</a></li>
                                <li><a href="javasctipt:void(0);">Triple Truffle Trotters</a></li>
                            </ul>
                        </div>
                        <!-- end footer-box-b -->
                    </div>
                    <!-- end col -->
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="footer-box-c">
                            <h3>Contact Us</h3>
                            <p>
                                <i class="fa fa-map-signs" aria-hidden="true"></i>
                                <span>103 Abc Building, St Albans Road, Mumbai</span>
                            </p>
                            <p>
                                <i class="fa fa-mobile" aria-hidden="true"></i>
                                <span>
                                    +91 1234567891
                                </span>
                            </p>
                            <p>
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                                <span><a href="#">support@sudama.com</a></span>
                            </p>
                        </div>
                        <!-- end footer-box-c -->
                    </div>
                    <!-- end col -->
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="footer-box-d">
                            <h3>Opening Hours</h3>

                            <ul>
                                <li>
                                    <p>Monday - Thursday </p>
                                    <span> 11:00 AM - 9:00 PM</span>
                                </li>
                                <li>
                                    <p>Friday - Saturday </p>
                                    <span> 11:00 AM - 5:00 PM</span>
                                </li>
                            </ul>
                        </div>
                        <!-- end footer-box-d -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end footer-in-main -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
        <div id="copyright" class="copyright-main">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <h6 class="copy-title"> Copyright &copy; 2021 Sudama Resturant</h6>
                    </div>
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end copyright-main -->
    </div>
    <!-- end footer-box -->
</div>

resturant-manager-master/resturant-manager-master/templates/user/order.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
Login | Registration
{% endblock title %}

{% block extracss %}
<style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    /* Firefox */
    input[type=number] {
        -moz-appearance: textfield;
    }
</style>
{% endblock extracss %}

{% block content %}
<div id="login-register" class="banner full-screen-mode parallax">
    <div class="container pr">

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="banner-static">
                <div class="banner-text">
                    <div class="banner-cell mt-0 mt-sm-1 " style="padding-bottom: 0px;" id="login-block">
                        <h2>Order</h2>
                        <form method="POST" id="order-form">
                        <ul class="list-group" style="overflow-y: scroll;max-height: 300px;text-align: start;">                   
                            
                            {% csrf_token %}
                            
                            {% for i in foods %}
                            <li class="list-group-item" style="color: black;padding:5px 10px;">
                                <img src="{{i.image.url}}" alt="" style="max-width:30px;">
                                <b style="font-size: 15px;">{{i}}</b>
                                <small>({{i.description}}) ({{i.get_category_display}})</small>
                                &#8377;{{i.price}}
                                <span style="float:right;">
                                    <button type="button" class="btn btn-danger decrement" data-link="#input-{{i.id}}" style="padding:0px 4px;">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                    <input type="text" style="max-width:30px;align-items:flex-end;" value="0" name="{{i.id}}"
                                        id="input-{{i.id}}">
                                    <button type="button" class="btn btn-success increment" data-link="#input-{{i.id}}" style="padding:0px 4px;">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                    
                                </span>
                            </li>
                            {% endfor %}

                        
                        </ul>
                        <div class="reserve-book-btn text-center " style="padding-top:0px;display: flex;justify-content: space-around;">
                            {% if not user_has_reserved %}
                            <select name="table" id="" class="form-control" style="max-width: 150px;margin-top: auto;margin-bottom: auto;" required>
                                <option selected disabled>Select Table</option>
                                {% for i in table %}
                                <option value="{{i.id}}">{{i}}</option>    
                                {% endfor %}
                            </select>
                            {% endif %}
                            <button form="order-form" class="hvr-underline-from-center" style="color: white;" type="submit" id="submit">
                                ORDER NOW
                            </button>
                            
                        </div>
                    </form>
                    </div>
                </div>
                <!-- end banner-text -->
            </div>
            <!-- end banner-static -->
        </div>
        <!-- end col -->
    </div>
    <!-- end container -->
</div>
<!-- end banner -->
<img src="{% static 'user/images/ad_4.png' %}" alt="" style="width:100%;height:auto;">
{% endblock content %}


{% block extrajs %}
<script>
    $('.nav li').removeClass('active');
    $('#nav-order').addClass('active');
</script>
<script>
    $('.increment').click(function(){
        var element = $(this).attr('data-link');
        var val = $(element).val();
        val++;
        $(element).val(val);
    });
    $('.decrement').click(function(){
        var element = $(this).attr('data-link');
        var val = $(element).val();
        if( val > 0){
            val--;
        }
        $(element).val(val);
    });
</script>
{% endblock extrajs %}